// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4XcOqQ5mrnTD-eH8wrxffxVB3jTAsTWw',
    appId: '1:1065997072852:web:59a0a131e1ce5328797e41',
    messagingSenderId: '1065997072852',
    projectId: 'appbeta-e382b',
    authDomain: 'appbeta-e382b.firebaseapp.com',
    storageBucket: 'appbeta-e382b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp9FGAUY1S1ZBM8SRNN4lmOW9ck6ClQsU',
    appId: '1:1065997072852:android:f99944f8ceb970dc797e41',
    messagingSenderId: '1065997072852',
    projectId: 'appbeta-e382b',
    storageBucket: 'appbeta-e382b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD-WPvKq2FVBaZ7m-MYMCL_BXq6Lp5BJ0',
    appId: '1:1065997072852:ios:0d6d98e03b75d344797e41',
    messagingSenderId: '1065997072852',
    projectId: 'appbeta-e382b',
    storageBucket: 'appbeta-e382b.appspot.com',
    iosClientId: '1065997072852-tfu9m5dqj935p24vtecsbgddmbh6t50u.apps.googleusercontent.com',
    iosBundleId: 'com.example.appBeta',
  );
}
